name: README build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go run generate.go > README.md
      - uses: EndBug/add-and-commit@v9
        with:
          add: README.md
          default_author: github_actions